version: '3'

networks:
  default:
    external:
      name: dondesang_network

services:
  comments:
    image: nginx:stable-alpine
    container_name: comments
    ports:
      - "8004:80"
    volumes:
      - ../../comments:/var/www/html/comments
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    # PHP service need to be ready before our web server is initialized
      - comments_php
    networks: 
      - default

  comments_php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: comments_php
    tty: true
    volumes:
      - ../../comments:/var/www/html/comments
    ports:
      - "9004:9000"
    networks: 
      - default
