version: '3'

networks:
  default:
    external:
      name: dondesang_network

services:
  users:
    image: nginx:stable-alpine
    container_name: users
    ports:
      - "8003:80"
    volumes:
      - ../../users:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    # PHP service need to be ready before our web server is initialized
      - users_php
    networks: 
      - default

  users_php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: users_php
    tty: true
    volumes:
      - ../../users:/var/www/html
    ports:
      - "9003:9000"
    networks: 
      - default

  users_composer:
    image: composer:latest
    container_name: users_composer
    volumes:
      - ../../users:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - users_php
    networks:
      - default
