version: '3'

networks:
  default:
    external:
      name: dondesang_network

services:
  users:
    image: nginx:stable-alpine
    container_name: users
    ports:
      - "8001:80"
    volumes:
      - ../../users:/var/www/html/users
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    # PHP service need to be ready before our web server is initialized
      - users_php
    networks: 
      - default

  users_php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: users_php
    tty: true
    volumes:
      - ../../users:/var/www/html/users
    ports:
      - "9001:9000"
    networks: 
      - default
