version: '3'

networks:
  default:
    external:
      name: dondesang_network

services:
  messages:
    image: nginx:stable-alpine
    container_name: messages
    ports:
      - "8002:80"
    volumes:
      - ../../messages:/var/www/html/messages
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    # PHP service need to be ready before our web server is initialized
      - messages_php
    networks: 
      - default

  messages_php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: messages_php
    tty: true
    volumes:
      - ../../messages:/var/www/html/messages
    ports:
      - "9002:9000"
    networks: 
      - default
