version: '3'

networks:
  default:
    external:
      name: dondesang_network

services:
  messages:
    image: nginx:stable-alpine
    container_name: messages
    ports:
      - "8004:80"
    volumes:
      - ../../messages:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    # PHP service need to be ready before our web server is initialized
      - messages_php
    networks: 
      - default

  messages_php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: messages_php
    tty: true
    volumes:
      - ../../messages:/var/www/html
    ports:
      - "9004:9000"
    networks: 
      - default

  messages_composer:
    image: composer:latest
    container_name: messages_composer
    volumes:
      - ../../messages:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - messages_php
    networks:
      - default
