version: '3'

networks:
  default:
    external:
      name: dondesang_network

services:
  blog:
    image: nginx:stable-alpine
    container_name: blog
    ports:
      - "8003:80"
    volumes:
      - ../../blog:/var/www/html/blog
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    # PHP service need to be ready before our web server is initialized
      - blog_php
    networks: 
      - default

  blog_php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: blog_php
    tty: true
    volumes:
      - ../../blog:/var/www/html/blog
    ports:
      - "9003:9000"
    networks: 
      - default
