version: '3'

networks:
  default:
    external:
      name: dondesang_network

services:
  blog:
    image: nginx:stable-alpine
    container_name: blog
    ports:
      - "8005:80"
    volumes:
      - ../../blog:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    # PHP service need to be ready before our web server is initialized
      - blog_php
    networks: 
      - default

  blog_php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: blog_php
    tty: true
    volumes:
      - ../../blog:/var/www/html
    ports:
      - "9005:9000"
    networks: 
      - default

  blog_composer:
    image: composer:latest
    container_name: blog_composer
    volumes:
      - ../../blog:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - blog_php
    networks:
      - default
