# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - "client/**"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependenties
      run: |
        cd client
        npm install
    - name: run build
      run: |
        cd client
        npm run build --prod --base-href="/don-du-sang/"
    - name: copy dockerfile
      run: |
        cd client
        mv ./Dockerfile ./dist

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: don-du-sang--${{ github.run_id }}
        path: "client/dist/**"
    - name: Install gcloud
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk
  
  
  
  
  
  
  
  
  
  
  
  
  
  
